version: '3'

services:
  consul_server01:
    image: consul:1.10
    container_name: consul_server01
    hostname: consul_server01
    command: ['tail', '-f', '/dev/null']
    ports:
      - '8500:8500'
    volumes:
      - ./servers/server01:/etc/consul.d

  consul_server02:
    image: consul:1.10
    container_name: consul_server02
    hostname: consul_server02
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./servers/server02:/etc/consul.d

  consul_server03:
    image: consul:1.10
    container_name: consul_server03
    hostname: consul_server03
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./servers/server03:/etc/consul.d

  consul_client01:
    image: consul:1.10
    container_name: consul_client01
    hostname: consul_client01
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul01:/etc/consul.d

  consul_client02:
    image: consul:1.10
    container_name: consul_client02
    hostname: consul_client02
    command: ['tail', '-f', '/dev/null']
    volumes:
      - ./clients/consul02:/etc/consul.d
